# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: API test execution

on:
  push:
    branches: [ "main" ]
    

jobs:
  seleniumTestonLinux:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v4
    - name: Setting up JDK 11 for execution
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        

    - name: Running test on linux
      run: mvn clean test


  
  APITestonWindows:

    runs-on: windows-latest
    

    steps:
    - uses: actions/checkout@v4
    - name: Setting up JDK 11 for execution
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        

    - name: Running test on windows
      run: mvn clean test

  APITestonMac:

    runs-on: macos-latest
    

    steps:
    - uses: actions/checkout@v4
    - name: Setting up JDK 11 for execution
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        

    - name: Running test on mac
      run: mvn clean test



